spring:
  profiles:
    active: secret, common

---
spring.config.activate.on-profile: common

server:
  port: 8094

spring:
  security:
    user:
      name: admin
      password: admin
  data:
    rest:
      basePath: /api
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    banner-mode: "off"
  application:
    name: garagez
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aor.cpsuay4ugddy.ap-northeast-2.rds.amazonaws.com:3306/garagez
    username: garagez
    password: gez11qq11qq
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

# ✅ JWT 설정 추가
jwt:
  secret: mySuperSecretKeyForJwtTokenAuthenticationAndValidation1234
  expiration: 86400000  # 24시간 (1일)

# ✅ 로깅 설정 (Hibernate SQL 쿼리 및 Debug 설정)
logging:
  level:
    org:
      thymeleaf: DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# ✅ Swagger UI 활성화
springdoc:
  swagger-ui:
    enabled: true

# ✅ PortOne 결제 API 설정 (필요할 경우)
portone:
  secret_key: your_secret_key_here
  api:
    url: https://api.portone.io/v2
