spring:
  profiles:
    active: secret, common

---

spring.config.activate.on-profile: common

server:
  port: 8094

spring:
  data:
    rest:
      basePath: /api
  devtools:
    livereload:
      enabled: true # 브라우저 LiveReload 활성화
    restart:
      enabled: true  # 코드 변경 시 애플리케이션 자동 재시작
  main:
    banner-mode: "off"
  application:
    name: cardatabase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardb
    username: caruser
    password: 12345
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: DEBUG
    org:
      thymeleaf: DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

openapi:
  chatbot:
    url: "https://api.example.com/chatbot"
    api-key: "your-api-key"

portone:
  secret_key: your_secret_key_here
  api:
    url: https://api.portone.io/v2